# This file assumes you've got the nginx proxy Docker container
# already running and listening to Docker.

web:
    build: .
    env_file:
    	- .env
    environment:
        VIRTUAL_HOST: photon-lightswitch.sammarks.me
    ports:
        - "0.0.0.0:8480:8480" # Expose to make the TCP client happy.
