# This file assumes you've got the nginx proxy Docker container
# already running and listening to Docker.

web:
    build: .
    environment:
        VIRTUAL_HOST: photon-lightswitch.sammarks.me
    ports:
    	- 8480 # Expose to make the TCP client happy.
